import { APP_PERMISSIONS } from "./app-constant";

export type AppPermission = (typeof APP_PERMISSIONS)[number];

export type ErrorKey =
  | "UNKNOWN_ERROR"
  | "BUSINESS_RULE_VIOLATION"
  | "INSUFFICIENT_PERMISSION"
  | "FEATURE_NOT_IMPLEMENTED"
  | "UNSUPPORTED_CURRENCY"
  | "PAYMENT_METHOD_NOT_SUPPORTED"
  | "PROPERTY_IMMUTABLE"
  | "PROPERTY_NOT_INITIALIZED"
  | "PROPERTY_REQUIRED"
  | "INVALID_STATUS"
  | "INVALID_VALUE"
  | "INVALID_CREDENTIAL"
  | "INVALID_REQUEST_CONTEXT"
  | "NOT_FOUND"